exclude: 'app/assets/stylesheets/reset.scss'

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

linters:
  BorderZero:
    enabled: true
  ColorKeyword:
    enabled: true
  ColorVariable:
    enabled: true
  Comment:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: false
  FinalNewline:
    enabled: true
  HexLength:
    enabled: false
  HexNotation:
    enabled: false
  IdSelector:
    enabled: true
  ImportPath:
    enabled: true
  ImportantRule:
    enabled: false
  Indentation:
    enabled: true
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: true
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingSemicolon:
    enabled: true
  UnnecessaryParentReference:
    enabled: false
  UrlQuotes:
    enabled: false
  VendorPrefix:
    enabled: false
  ZeroUnit:
    enabled: false
