version: 2.1

orbs:
  cj: criticaljuncture/cj-orb@0.1

workflows:
  workflow:
    jobs:
      - cj/build_rails_image:
          branch: << pipeline.git.branch >>
          context: [ofr-ecr, cj-quay-base, orb-slack, pilot, sidekiq-pro, ofr-rails-test-credentials]
          ecr: true
          repo_image: federalregister-web
          lint_command: docker-compose -f docker/compose/ci.yml run web bash -c "rake jshint && coffeelint -f coffeelint.json -r app/assets/javascripts/"
          test_command: |
            docker-compose -f docker/compose/ci.yml run web bash -c "bin/wait_for_mysql && rake parallel:setup --trace && parallel_rspec -o '--tag ~no_ci'"
