shared: &shared
  attachments:
    aws:
      access_key_id: <%= ENV['ATTACHMENTS_AWS_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['ATTACHMENTS_AWS_SECRET_ACCESS_KEY'] %>

  circle_ci:
    reg_gov_build_token: <%= ENV['CIRCLE_CI_REG_GOV_BUILD_TOKEN'] %>

  comment_ip_salt: <%= ENV['COMMENT_IP_SALT'] %>

  data_dot_gov:
    api_key: <%= ENV['DATA_DOT_GOV_API_KEY'] %>
    primary_comment_api_key: <%= ENV['REG_DOT_GOV_PRIMARY_COMMENT_API_KEY'] %>
    secondary_comment_api_key: <%= ENV['REG_DOT_GOV_SECONDARY_COMMENT_API_KEY'] %>

  email_salt: <%= ENV['EMAIL_SALT'] %>

  fr_profile:
    basic_username: <%= ENV['PROFILE_BASIC_USERNAME'] %>
    basic_password: <%= ENV['PROFILE_BASIC_PASSWORD'] %>

  jwt_secret: <%= ENV['JWT_SECRET'] || "development_secret_key" %>
  honeybadger_csp_api_key: <%= ENV['HONEYBADGER_CSP_API_KEY'] || '' %>

  omniauth:
    oidc_url: <%= ENV['OIDC_URL'] || Settings.services.fr_profile_url %>
    oidc_application_id: <%= ENV['OIDC_APPLICATION_ID'] || '6f0e6dd9a23104b445f208ef7a00e63a01752ad950406a96478759e761ddeb2d' %>
    oidc_secret: <%= ENV['OIDC_SECRET'] || '2c5bc1795f53a69ccad171c09871a8db76adb88ca0408bb24be872fe43556ad7' %>
    oidc_redirect_url: <%= ENV['OIDC_REDIRECT_URL'] || 'http://localhost:4000/auth/ofr/callback' %>

  recaptcha:
    public: <%= ENV['RECAPTCHA_PUBLIC'] %>
    private: <%= ENV['RECAPTCHA_PRIVATE'] %>

  redis:
    host: <%= ENV['REDIS_PORT_6379_TCP_ADDR'] || '127.0.0.1' %>
    port: <%= ENV['REDIS_PORT_6379_TCP_PORT'] || 6379 %>
    db: <%= ENV['REDIS_DB'] || 0 %>

  secret_key_base: <%= ENV['RAILS_SESSION_KEY'] || ENV['SECRET_KEY_BASE'] %>

  sendgrid:
    username: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>


development:
  <<: *shared
  jwt_secret: <%= ENV['JWT_SECRET'] || "development_secret_key" %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "b9ceab1c8deeb3bb4f3558d05ff0877cf5eed7d398b7b6b94f732a9d649ad019ec84f649210d2851b38ae1d724dd8bac2743bca4432b1969372d1d5623c3fcfc" %>
  attachments:
    aws:
      access_key_id: <%= ENV['ATTACHMENTS_AWS_ACCESS_KEY_ID'] || 'XXX' %>
      secret_access_key: <%= ENV['ATTACHMENTS_AWS_SECRET_ACCESS_KEY'] || 'XXX' %>

test:
  <<: *shared
  jwt_secret: <%= ENV['JWT_SECRET'] || "development_secret_key" %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || "2e7097d7c58ca6edcac8fd199c8ff97686c8d0a8af98943adb476122ec9c608da6ac35b8af03c175b21393a7c170087e375c22bbe7229d2f8caecf8eae0c2798" %>
  comment_ip_salt: '1234567890'
  data_dot_gov:
    api_key: '123456789'
    primary_comment_api_key: 'AAABBBCCC'
    secondary_comment_api_key: 'XXXYYYZZZ'
  attachments:
    aws:
      access_key_id: <%= ENV['ATTACHMENTS_AWS_ACCESS_KEY_ID'] || 'XXX' %>
      secret_access_key: <%= ENV['ATTACHMENTS_AWS_SECRET_ACCESS_KEY'] || 'XXX' %>

staging:
  <<: *shared

production:
  <<: *shared
