aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
circle_ci:
  reg_gov_build_token: <%= ENV['CIRCLE_CI_REG_GOV_BUILD_TOKEN'] %>
data_dot_gov:
  api_key: <%= ENV['DATA_DOT_GOV_API_KEY'] %>
email_salt: <%= ENV['EMAIL_SALT'] %>
honeybadger_api_key: <%= ENV['HONEYBADGER'] %>
recaptcha:
  public: <%= ENV['RECAPTCHA_PUBLIC'] %>
  private: <%= ENV['RECAPTCHA_PRIVATE'] %>
sendgrid:
  username: <%= ENV['SENDGRID_USERNAME'] %>
  password: <%= ENV['SENDGRID_PASSWORD'] %>
session_secret_token: <%= ENV['RAILS_SESSION_KEY'] %>
