# urls for mailers, redirects, etc - where routes aren't available
app_url: 'https://www.federalregister.gov'
permitted_hosts: <%= ENV["PERMITTED_HOSTS"] || "" %>
canonical_host: 'https://www.federalregister.gov'
fr_comment_url: 'https://www.federalregister.gov/my/comments'

csp:
  report_only: <%= ENV["CSP_REPORT_ONLY"] || false %>
  esi_unifying_nonce:  <%= ENV["ESI_UNIFYING_NONCE"] || 'REPLACE_ME_NONCE' %> #Nginx will replace this value to ensure all ESIs share the same nonce

external_modal_domain_whitelist:
  - "www.archives.gov"
  - "www.govinfo.gov"
  - "federalregister.tenderapp.com"
  - "s3.amazonaws.com/public-inspection."
  - "s3.amazonaws.com/archives."
  - "agency-logos.federalregister.gov"
  - "archives.federalregister.gov"
  - "www.ecfr.gov"
  - "images.federalregister.gov"
  - "img.federalregister.gov"
  - "public-inspection.federalregister.gov"
  - "uploads.federalregister.gov"

feature_flags:
  announcements: <%= ActiveModel::Type::Boolean.new.cast( ENV.fetch("FEATURE_FLAG_ANNOUNCEMENTS", false) ) %>
  events_search: false
  fr_index_pdfs: true
  honeybadger_js: <%= ActiveModel::Type::Boolean.new.cast(ENV.fetch("FEATURE_FLAG_HONEYBADGER_JS", false)) %>
  unified_agenda:
    search: false
  regulations_dot_gov:
    submit_comments: <%= ENV["REG_GOV_SUBMIT_COMMENTS"] || false %>
  regulatory_plan: false
  # google charts image api is deprecated - reimplement in js
  report_deprecations: <%= ActiveModel::Type::Boolean.new.cast( ENV.fetch("REPORT_DEPRECATIONS", false) ) %>
  sparklines:
    agencies: false
    topics: false
    suggested_searches: false
    my_fr:
      subscriptions: false
  search:
    location: true
  subscriptions:
    deliver: <%= ENV['DELIVER_SUBSCRIPTIONS'].present? ? ActiveModel::Type::Boolean.new.cast(ENV['DELIVER_SUBSCRIPTIONS']) : true %>
    deliver_pil: <%= ENV['DELIVER_PIL_SUBSCRIPTIONS'].present? ? ActiveModel::Type::Boolean.new.cast(ENV['DELIVER_PIL_SUBSCRIPTIONS']) : true %>
  use_carrierwave_images_in_api: <%= ActiveModel::Type::Boolean.new.cast(ENV['USE_CARRIERWAVE_IMAGES_IN_API']) || false %>

federal_register:
  api_url: '<%= ENV["FR_API_URL"] %>'
  base_url: '<%= ENV["FR_BASE_URL"] %>'
  internal_api_url: '<%= ENV["FR_INTERNAL_API_URL"] %>'
  internal_base_url: '<%= ENV["FR_INTERNAL_BASE_URL"] %>'

federal_register_archives:
  api_url: '<%= ENV["FR_ARCHIVES_API_URL"] %>'

# generic switch for deciding when to raise exception or notify honeybadger
notify_honeybager: true

officialness:
  start_date: 2025-05-01

regulations_dot_gov:
  # don't output calls to reg.gov in stdout
  debug_output_enabled: false
  api_base_url: <%= ENV["REG_GOV_API_BASE_URL"] || 'https://api-staging.regulations.gov/v4' %>

  throttle:
    at: <%= ENV["WEB_REG_GOV_JOBS_THROTTLE_AT"] || 1 %>
    per: <%= ENV["WEB_REG_GOV_JOBS_THROTTLE_PER"] || 60 %>

# document page full text rendering - false means use esi's
render_documents_from_raw_xml: false

rss_helper:
  url: "https://www.federalregister.gov"

varnish:
  host: <%= ENV["VARNISH_ADDR"] || 'varnish' %>
  port: 6082

services:
  fr_profile_internal_url: '<%= ENV["FR_PROFILE_INTERNAL_BASE_URL"] %>'
  fr_profile_url: '<%= ENV["FR_PROFILE_BASE_URL"] %>'

zendesk:
  api_url: <%= ENV["ZENDESK_API_URL"] || 'https://ofr.zendesk.com/api/v2' %>
