regulations_dot_gov:
  # don't output calls to reg.gov in stdout
  debug_output_enabled: false

# document page full text rendering - false means use esi's
render_documents_from_raw_xml: false

# urls for mailers, redirects, etc - where routes aren't available
fr_comment_url: 'https://www.federalregister.gov/my/comments'
