---
:concurrency: 1
:queues:
  - issue_processor
  - subscriptions
  - issue_reprocessor
  - issue_recompilator
  - web_reg_gov

# env specific settings if needed
#development:
#staging:
#production:
