vcr:
  enabled: true
  library_dir: "vcr/dev"
  cassette: 'development'
  ignore_hosts: ['127.0.0.1', 'localhost', 'fr2.dev']
  ignore_paths: [] #["^/api/v1/documents"]
  re_record_interval: 7 #days
  log_output: false
varnish:
  enable_cache_headers: true
  ignore_paths: ""
federal_register:
  api_url: 'http://127.0.0.1:8080/api/v1'
regulations_dot_gov:
  debug_output_enabled: true
