active_model_serializers:
  # default to enabled for dev environments (opposite other environments)
  disable_logging: false

app:
  # document page full text rendering
  document_render:
    # should we get precompiled content from remote (eg in development)
    from_remote: true
  subscriptions:
    deliver: false
    deliver_pil: false

lograge:
  enabled: false

regulations_dot_gov:
  debug_output_enabled: true

# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  image_variants: img.fr2.criticaljuncture.org
  private_images: private.images.fr2.local
  public_images: images.fr2.local

varnish:
  enable_cache_headers: false
  host: varnish

####################################
# DEVELOPMENT ONLY SETTINGS
####################################

permitted_hosts:

vcr:
  enabled: true
  library_dir: "vcr/dev"
  cassette: 'development'
  ignore_hosts: ['127.0.0.1', 'localhost', 'fr2.dev', 'dev-fr2.criticaljuncture.org']
  ignore_paths: [] #["^/api/v1/documents"]
  re_record_interval: 7 #days
  log_output: false
  max_cassette_size: 4.0 #Mb
