external_modal_domain_whitelist:
  - "www.federalregister.gov"
  - "www.archives.gov"
  - "www.govinfo.gov"
  - "federalregister.tenderapp.com"
  - "fr2.criticaljuncture.org"

vcr:
  enabled: true
  library_dir: "vcr/dev"
  cassette: 'development'
  ignore_hosts: ['127.0.0.1', 'localhost', 'fr2.dev', 'dev-fr2.criticaljuncture.org']
  ignore_paths: [] #["^/api/v1/documents"]
  re_record_interval: 7 #days
  log_output: false
  max_cassette_size: 4.0 #Mb
varnish:
  host: 127.0.0.1
  enable_cache_headers: true

regulations_dot_gov:
  debug_output_enabled: true


# APPLICATION SETTINGS
federal_register:
  api_url: 'https://www.federalregister.gov/api/v1'
  base_url: 'https://www.federalregister.gov'

federal_register_archives:
  api_url: 'http://localhost:3020'

app_url: 'http://127.0.0.1:8080'
canonical_host: 'http://localhost:6081'

# document page full text rendering
render_documents_from_raw_xml: false
render_documents_from_staging: true

# urls for mailers, redirects, etc
fr_comment_url: 'http://127.0.0.1:8080/my/comments'

# generic switch for deciding when to raise exception or notify honeybadger
notify_honeybager: false

# using browser sync
browser_sync:
  enabled: false

# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  private_images: private.images.fr2.local
  public_images: images.fr2.local

services:
  fr_profile_url: "https://ecfr.criticaljuncture.org"
