vcr:
  enabled: true
  library_dir: "vcr/dev"
  cassette: 'development'
  ignore_hosts: ['127.0.0.1', 'localhost', 'fr2.dev']
  ignore_paths: [] #["^/api/v1/documents"]
  re_record_interval: 7 #days
  log_output: false
  max_cassette_size: 1.0 #Mb
varnish:
  enable_cache_headers: true
  ignore_paths: ""
federal_register:
  api_url: 'http://127.0.0.1:8080/api/v1'
  base_uri: 'http://127.0.0.1:8080'
regulations_dot_gov:
  debug_output_enabled: true


# APPLICATION SETTINGS
app_url: 'http://127.0.0.1:8080'

# document page full text rendering - false means use esi's
render_documents_from_raw_xml: true

# urls for mailers, redirects, etc
fr_comment_url: 'http://127.0.0.1:8080/my/comments'

# generic switch for deciding when to raise exception or notify honeybadger
notify_honeybager: false

# using browser sync
browser_sync:
  enabled: false
