federal_register:
  api_url: 'https://fr-official.criticaljuncture.org/api/v1'
  base_uri: 'https://fr-official.criticaljuncture.org'

# APPLICATION SETTINGS
app_url: 'https://fr-official.criticaljuncture.org'

# urls for mailers, redirects, etc - where routes aren't available
fr_comment_url: 'https://fr-official.criticaljuncture.org/my/comments'

# officialness:
#   start_date: 2015-12-01

# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  private_images: private.images.fr-official.criticaljuncture.org
  public_images: images.fr-official.criticaljuncture.org
