# urls for mailers, redirects, etc - where routes aren't available
app_url: 'https://www.federalregister.gov'
fr_comment_url: 'https://www.federalregister.gov/my/comments'
rss_helper:
  url: "federalregister.gov"

regulations_dot_gov:
  base_uri: <%= ENV["REG_GOV_BASE_URL"] || 'https://api.data.gov/regulations/v3' %>

feature_flags:
  allow_bot_traffic: true
  regulations_dot_gov:
    submit_comments: <%= ENV["REG_GOV_SUBMIT_COMMENTS"] || true %>


# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  image_variants: img.federalregister.gov
  private_images: private.images.federalregister.gov
  public_images: images.federalregister.gov
