# APPLICATION SETTINGS
app_url: 'https://fr2.criticaljuncture.org'

# urls for mailers, redirects, etc - where routes aren't available
fr_comment_url: 'https://fr2.criticaljuncture.org/my/comments'

# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  private_images: private.images.fr2.criticaljuncture.org
  public_images: images.fr2.criticaljuncture.org
