database:
  name: federal_register_web_staging

# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  image_variants: img.fr2.criticaljuncture.org
  private_images: private.images.fr2.criticaljuncture.org
  public_images: images.fr2.criticaljuncture.org
