# APPLICATION SETTINGS
app_url: 'https://fr2.criticaljuncture.org'
canonical_host: 'https://fr2.criticaljuncture.org'
fr_comment_url: 'https://fr2.criticaljuncture.org/my/comments'

external_modal_domain_whitelist:
  - "www.federalregister.gov"
  - "www.archives.gov"
  - "www.govinfo.gov"
  - "federalregister.tenderapp.com"
  - "fr2.criticaljuncture.org"


# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.federalregister.gov
  private_images: private.images.fr2.criticaljuncture.org
  public_images: images.fr2.criticaljuncture.org
