lograge:
  enabled: false

regulations_dot_gov:
  debug_output_enabled: true

redis:
  host: 127.0.0.1

# Make any updates -api-core also
s3_buckets:
  zipped_eps_images: eps.images.test.federalregister.gov
  private_images: private.test.images.fr2.dev
  public_images: test.images.fr2.dev

services:
  fr:
    api_core:
      internal_base_url: https://www.federalregister.gov/api/v1
    web:
      internal_base_url: https://www.federalregister.gov
  ofr:
    profile:
      base_url: "https://example.com/my/profile"
