version: '2'

services:
  web:
    image: 264372021245.dkr.ecr.us-east-1.amazonaws.com/federalregister-web:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      WEB_PORT: 3000
      PASSENGER_MIN_INSTANCES: 2
      REDIS_PORT_6379_TCP_ADDR: redis
      HONEYBADGER_API_KEY: ''
      ATTACHMENTS_AWS_ACCESS_KEY_ID: 'XXX'
      ATTACHMENTS_AWS_SECRET_ACCESS_KEY: 'XXX'
      RAILS_SESSION_KEY: XXXXxxxxXXXXxxxxXXXXxxxxXXXXxxxx
      SETTINGS__CONTAINER__PROCESS: rails
      REG_GOV_API_KEY: xxxxxxxxxxxxxxxxxx
      SETTINGS__REDIS__HOST: redis
    restart: always

  mysql:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'

  redis:
    image: redis:3.2-alpine
    expose:
      - "6379"
